### PR TITLE
Add support for Cyrillic script

### PR DESCRIPTION
**Pull request by kugimiya**
So, some geeks like dat font, and added cyrillic bitmaps for their language support.

### CODE REVIEW

**Comment by alexmyczko** [comment]
@ntwk are you going to merge this?

**Comment by alexmyczko** [comment]
@kugimiya Would you say your addition is the same license as the recently created license for the font? If so, I would like to add your extension to the Debian packaging of fonts-atarist...

**Comment by kugimiya** [comment]
@alexmyczko Yes, the same license as parent repo (this repo). I will be very happy if you add my extension to your package :)

**Comment by ntwk** [comment]
@alexmyczko, I hadn't planned to add any more characters to the original set but I'm open to it if the additions are of sufficient quality and consonant with the look and feel of the font.  That said, I don't know the Cyrillic script so I can't vouch for the accuracy and quality of these proposed additions.

Despite my limited knowledge here, I did a review and found the following issues:

1. The value of the `STARTCHAR` field of each new glyph should match the Unicode 'Name' property specified at the corresponding Unicode code point.  See the `STARTCHAR` values of the original glyphs for reference.  A list of the Unicode Names for each code point can be found [here](http://www.unicode.org/Public/UNIDATA/NamesList.txt).
2. The glyph at `ENCODING 192` (U+00C0) was changed and is now incorrect
3. The glyph at `ENCODING 193` (U+00C1) was added but it appears to be incorrect.  Further still, the glyph at this code point (LATIN CAPITAL LETTER A WITH ACUTE) is not part of of the Cyrillic script and appears to be a spurious addition.
4. The glyph at `ENCODING 194` (U+00C2) was added but it appears to be incorrect.  Again, the glyph at this code point (LATIN CAPITAL LETTER A WITH CIRCUMFLEX) is not part of of the Cyrillic script and appears to be a spurious addition.
5. Commit messages should be amended to be written entirely in English.

**Comment by kugimiya** [comment]
@ntwk @alexmyczko hi, I can fix this issues, please await my next reply with changes

**Comment by kugimiya** [comment]
@ntwk hi, I fixed this issues, can u review please? :)

**Comment by ntwk** [comment]
@kugimiya, looks good.  I made a few minors revisions:

1. I reverted the value of `_GBDFED_INFO`.
2. I updated the README to mention Cyrillic support.

I'll merge your changes to the master branch if these revisions look good to you.

**Comment by kugimiya** [comment]
@ntwk yeah, looks good :)

**Pull request merged**
